'use client'
import React, { useState } from "react";
import type {FC} from 'react';
import Dexie from "dexie";
import { patientsIndexedDb, patientProfileTable } from "@/database/db"; 
import type { IPatientProfile } from "@/database/db"; 
import { ImportOptions, exportDB, importInto, peakImportFile } from "dexie-export-import";
import { DexieExportJsonStructure } from "dexie-export-import/dist/json-structure";
import { JsonStream } from "dexie-export-import/dist/json-stream";
import UploadForm from "./UploadForm";
// import { saveAs } from 'file-saver';
// import _ from 'lodash';
// import prettyBytes from 'pretty-bytes';
// import ReactTimeAgo from 'react-time-ago';
// import { useEffectOnce } from 'react-use';

const AddPatientForm: FC = () => {  // { defaultAge } = { defaultAge: 21 }
  const [patientName, setPatientName] = useState('');
  const [status, setStatus] = useState(''); 
  const [dbOperationStatus, setDbOperationStatus] = useState(<></>);
  const [validateImport, setValidateImport] = useState('');
  const [importProgress, setImportProgress] = useState(0); 
  const [importableBlob, setImportableBlob] = useState<Blob | undefined>();
  const [loadedDocs, setLoadedDocs] = useState(0);
  const [totalDocs, setTotalDocs] = useState(0);
  const [mostRecentVersions, setMostRecentVersions] = useState([]);
  const DEFAULT_KILOBYTES_PER_CHUNK = 1024; // When importing blob
  const DEFAULT_ROWS_PER_CHUNK = 2000; // When exporting db

  const demoVcfGenomeFile = `
  # This data file generated by 23andMe at: Mon Nov 11 20:13:24 2013
  #
  # Below is a text version of your data.  Fields are TAB-separated
  # Each line corresponds to a single SNP.  For each SNP, we provide its identifier 
  # (an rsid or an internal id), its location on the reference human genome, and the 
  # genotype call oriented with respect to the plus strand on the human reference sequence.
  # We are using reference human assembly build 37 (also known as Annotation Release 104).
  # Note that it is possible that data downloaded at different times may be different due to ongoing 
  # improvements in our ability to call genotypes. More information about these changes can be found at:
  # https://www.23andme.com/you/download/revisions/
  # 
  # More information on reference human assembly build 37 (aka Annotation Release 104):
  # http://www.ncbi.nlm.nih.gov/mapview/map_search.cgi?taxid=9606
  #
  # rsid	chromosome	position	genotype
  rs4477212	1	82154	AA
  rs3094315	1	752566	AA
  rs3131972	1	752721	GG
  rs12562034	1	768448	AG
  rs12124819	1	776546	AA
  rs11240777	1	798959	AG
  rs6681049	1	800007	CC
  rs4970383	1	838555	CC
  rs4475691	1	846808	CT
  rs7537756	1	854250	AG
  rs13302982	1	861808	GG
  rs1110052	1	873558	GT
  rs2272756	1	882033	GG
  rs3748597	1	888659	CC
  rs13303106	1	891945	AG
  rs28415373	1	893981	CC
  rs13303010	1	894573	AG
  rs6696281	1	903104	CC
  rs28391282	1	904165	GG
  rs2340592	1	910935	AG
  rs13303118	1	918384	GT
  rs6665000	1	924898	AA
  rs2341362	1	927309	CC
  rs9777703	1	928836	TT
  rs1891910	1	932457	AG
  rs9697457	1	934345	GG
  rs35940137	1	940203	GG
  rs3128117	1	944564	CC
  rs2465126	1	947034	AA
  `;

  const addPatientProfile = async (event) => {
    event.preventDefault()
    // setDbOperationStatus(<Alert severity='info'>Importing...</Alert>)

    // Import from Blob or File to Dexie instance:
    // const patientsIndexedDb = await Dexie.import(blob, [options]);
    // const textData = "Hello, this is a Blob example.";
    // const blob: Blob | JsonStream<DexieExportJsonStructure> = new Blob([textData], { type: "text/plain" }); 

    try {
      // const importOptions: ImportOptions = {
      //   progressCallback: updateImportProgress,
      //   clearTablesBeforeImport: true,
      //   acceptVersionDiff: true
      // }
      
      // const file = event.target.files?.[0];
      // if (!file) {
      //     console.log("No file selected");
      //     setImportableBlob(undefined);
      //     return;
      // }

      const blob = new Blob([demoVcfGenomeFile]);
      // const blob = new Blob([file], { type: file.type });
      
      // const importMeta = await peakImportFile(blob);
      // if (!importMeta || importMeta?.formatName !== 'dexie' || importMeta.data.databaseName !== 'parseqDB') {
      //     console.error("Not a Parseq database", importMeta);
      //     // setDbOperationStatus(<Alert severity='warning'>Selected file seemed invalid. See console for details.</Alert>);
      //     setImportableBlob(undefined);
      //     return;
      // }
      
      // setImportableBlob(blob);
      // setValidateImport('');
      
      // await importInto(patientsIndexedDb, importableBlob, importOptions);

      // const firstPart = blob.slice(0,100);  
      // function readBlob(blob: Blob): Promise<string> {
      //   return new Promise((resolve, reject) => {
      //     const reader = new FileReader();
      //     reader.onabort = ev => reject(new Error("file read aborted"));
      //     reader.onerror = ev => reject((ev.target as any).error);
      //     reader.onload = ev => resolve((ev.target as any).result);
      //     reader.readAsText(blob);
      //   });
      // }
    } catch (error) {
        // setDbOperationStatus(<Alert severity='error'>Import failed: {error?.toString()}</Alert>)
        console.error(error);
    } finally {
        setImportableBlob(undefined); 
    }

    // const patientProfile: IPatientProfile = { 
    //   patient_id: event.target.name.id,
    //   patient_name: event.target.name.value, 
    // }
   
    // try {
    //   const patientId = await patientProfileTable.add(patientProfile);
    //   event.target.reset()
    //   setStatus(`Patient ${patientName} successfully added: patientId ${patientId}`);
    //   setPatientName('');
    // } catch (error) {
    //   setStatus(`Failed to add ${patientName}: ${error}`);
    //   console.error(`Failed to add ${patientName}: ${error}`);
    // } 
  }

  // const onConfirmImportDialogClose = useCallback((event: any) => {
  //     setConfirmImportDialogOpen(false);
  //     if (event?.target?.id === "import") {
  //         doImport();
  //     }
  // }, [doImport]);

  return (
    <>
      <p>Status: {status}</p>
      {/* <form onSubmit={addPatientProfile}>
          <label htmlFor="name">Patient File Name:</label>
          <input
            id="name" name="name"
            type="text"
            value={patientName}
            onChange={(ev) => setPatientName(ev.target.value)}
          /> 
          <button 
              className="flex-1 rounded px-3 py-1 mt-3 text-xs border-zinc-950 dark:border-zinc-200 bg-slate-100 dark:bg-gray-950 text-zinc-950 dark:text-white"
              type="submit">
              Add
            </button> 
      </form> */}

       <div><h2 className="text-2xl font-bold text-gray-900">Upload Patient File</h2><div className="mt-2 px-7 py-3"><UploadForm /></div></div>

      <div>
          {/* <button
          className="rounded bg-gray-200 px-3 py-1 mt-3 text-xs"
          onClick={uploadDNAFile}
          >
              Upload DNA File
          </button> */}
          {/* <Select patientProfiles={patientProfiles} error={error} handlePatientChange={handlePatientChange} /> */}
      </div>

      {/* {confirmImportDialog} 
      <button
          // component="label"
          // variant='outlined'
          // disabled={activity !== undefined}
        >
          {/* <FontAwesomeIcon icon={faUpload} /> 
          &nbsp;Import Parseq database
          <input hidden type="file" accept='.json'
            onClick={
              //@ts-ignore
              e => e.target.value = null // Ensures onChange fires even if same file is re-selected.
            }
            onChange={async (event) => {
              const file = event.target.files?.[0];
              if (!file) {
                  console.log("No file selected");
                  setImportableBlob(undefined);
                  return;
              }
              const blob = new Blob([file], { type: file.type });
              const importMeta = await peakImportFile(blob);
              if (!importMeta || importMeta?.formatName !== 'dexie' || importMeta.data.databaseName !== 'parseqDB') {
                  console.error("Not a Parseq database", importMeta);
                  // setDbOperationStatus(<Alert severity='warning'>Selected file seemed invalid. See console for details.</Alert>);
                  setImportableBlob(undefined);
                  return;
              }
              setImportableBlob(blob);
              setValidateImport('');
              // setConfirmImportDialogOpen(true);
          }} />                                 
      </button>
      {activity === 'importing' &&
          <span>
              <Typography fontSize={'0.75em'}>Importing: </Typography>
              <LinearProgressWithLabel value={importProgress} />
          </span>
      } */}

      <style jsx>{`
          p, input, label, select, button {
              font-size: 0.8em;
          }
          form {
            padding: 0.5em;
            border: 1px rgb(236, 232, 232) solid;
          }
          label {
            padding: 0 0.5em; 
          }
          input {
            padding: 0 0.5em; 
            border: 1px rgb(222, 221, 221) solid;
          }
          button {
            padding: 0 0.5em; 
          }
      `}</style>
    </>
  );
}

export default AddPatientForm;
//   <h2 className="table-header">Patient Gene Variants</h2>
//   <UploadForm /> 
//   <hr />
//   {status}
// const AddPatientForm = dynamic(() => import('@/components/AddPatientForm'), {
//   ssr: false,
// })
// const UploadForm = dynamic(() => import('@/components/UploadForm'), {
//   ssr: false,
// })
// const GenomeList = dynamic(() => import('@/components/GenomeList'), {
//   ssr: false,
// })

// async function addPatientGenome() {
//   console.log('addPatientGenome');
//   try {
//     const id = await patientsIndexedDb.patientGenome.add({
//       rsid: '1',
//       patient_id: '1',
//       chromosome: '1',
//       position: '1',
//       genotype: 'AA'
//     });
//     console.log('Added');
//     setStatus(`Gene variant successfully added. Got id ${id}`); 
//   } catch (error) {
//     console.log('Not added');
//     setStatus(`Failed to add patient gene variant: ${error}`);
//   }
// } 
// //   <button onClick={addPatientGenome}>Add Patient Gene Variant</button>
